name: ${pluginName}Plugin
version: ${version}
main: ${group}.${packageName}.plugin.${pluginName}Plugin
api-version: 1.19
libraries:
  - io.github.muqhc:skyguifx:0.1.2
  - io.github.monun:kommand-core:3.1.3